version: '3.8'

services: 
  orchid-python-api:
    image: orchid-python-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    restart: unless-stopped
    networks:
      - sep-orchid-lab-network
    environment:
      # Workers configuration
      # RAM < 2GB: WORKERS=1
      # RAM 2-4GB: WORKERS=2 (recommended for concurrent users)
      # RAM > 4GB: WORKERS=4 (high traffic)
      - WORKERS=2
    command: /bin/sh -c "rm -rf /app/cache && python orchid_api.py"

networks:
  sep-orchid-lab-network:
    external: true
    driver: bridge